// src/lib/components/models/model-details/toolbar/set-default.svelte
<script lang="ts">
  import { setDefaultModel } from "$lib/commands/models"
  import { Button } from "$lib/components/ui/button"
  import { defaultModel } from "$lib/stores/models"
  import { toast } from "svelte-sonner"

  let { model }: { model: string } = $props()
</script>

<Button
  onclick={() => {
    // Optimistic update
    const prevModel = $defaultModel
    defaultModel.set(model)
    setDefaultModel(model)
      .catch((err) => {
        if (prevModel) {
          defaultModel.set(prevModel)
          return
        }
        toast.error(err)
      })
  }}
>
  Set default
</Button>

// src/lib/components/model-page/toolbar-items/set-default.tsx
import { Accessor } from "solid-js";
import { Button } from "../../ui/button";
import { useModelContext } from "~/lib/contexts/model-list";
import { setDefaultModel } from "~/lib/commands/models";
import { toast } from "solid-sonner";

export interface SetDefaultProps {
  model: Accessor<string>;
}

export default function SetDefault(props: SetDefaultProps) {
  const modelContext = useModelContext();

  const model = props.model;
  const defaultModel = modelContext?.defaultModel;

  return (
    <Button onClick={() => {
      // Optimistic update
      const prev = defaultModel?.();
      const m = model();

      modelContext?.setDefault(m);
      setDefaultModel(m)
        .catch((err) => {
          if (prev) {
            modelContext?.setDefault(prev);
          }

          toast.error(err);
        });
    }}>
      Set default
    </Button>
  );
}
