// src/lib/components/chat-sessions/prompt-input/index.tsx
import { Show, createEffect, createMemo, createSignal, onCleanup } from "solid-js";
import { getChatHistory, submitChat } from "~/lib/contexts/globals/chat-history";
import {
  clearInputPrompt,
  getInputPrompt,
  hidePromptBar,
  isSubmittable,
  setHidePromptBar,
  setInputPrompt,
} from "~/lib/contexts/globals/prompt-input";
import { Button } from "../../ui/button";
import { ArrowUpIcon, ChevronDownIcon, } from "lucide-solid";
import { cn } from "~/lib/utils/class-names";
import { ImageInfoReturn, ImagePreview } from "../../custom-ui/image-preview";
import { getThumbnailBase64 } from "~/lib/commands/image";
import { produce } from "solid-js/store";
import { PromptInputToolbar } from "./toolbar";
import { LoaderSpin } from "../../loader-spin";
import { emit } from "@tauri-apps/api/event";
import autosize from "autosize";
import { toSrcString } from "~/lib/utils/images";
import { getCurrentModel } from "~/lib/contexts/globals/current-model";

export function PromptInput() {
  const [formRef, setFormRef] = createSignal<HTMLFormElement | undefined>(undefined);
  const [textEntryRef, setTextEntryRef] = createSignal<HTMLTextAreaElement | undefined>(undefined);

  const [status, setStatus] = createSignal<"submitting" | "responding" | undefined>(undefined);

  const onRespond = () => {
    setStatus("responding");
    clearInputPrompt();
  };

  const clearStatus = () => setStatus(undefined);

  const fetcher = async (src: string) => {
    const image = await getThumbnailBase64(src);
    return {
      result: toSrcString(image.mime, image.base64),
      origin: image.path,
    } satisfies ImageInfoReturn;
  };

  const deletePreviewItem = (i: number) => {
    setInputPrompt("imagePaths", produce((paths) => {
      if (paths) {
        paths.splice(i, 1);
      }
    }));
  }

  const busy = createMemo(() => status() === "responding" || getChatHistory()?.chats.at(-1)?.status === "sending");

  createEffect(() => {
    const ref = textEntryRef();
    if (ref) {
      autosize(ref);
    }
  });

  onCleanup(() => {
    const textEntry = textEntryRef();
    if (textEntry) {
      autosize.destroy(textEntry);
    }
  });

  const SubmitButton = () => (
    <Button
      size="icon"
      class="rounded-full"
      type="submit"
      disabled={!!status() || !isSubmittable()}
      title="Send prompt"
    >
      <Show when={status() === "submitting"} fallback={<ArrowUpIcon class="size-6!" />}>
        <LoaderSpin class="size-6!" />
      </Show>
    </Button>
  );

  const stopGeneration = async () => await emit("cancel-gen");

  return (
    <form
      ref={setFormRef}
      class="relative border-t border-l border-r border-secondary bg-background flex flex-col gap-1.5 px-2.5 pt-0 pb-2 rounded-t-2xl overflow-hidden transition-[margin] -mt-4 z-30"
      style={{
        "margin-bottom": `-${hidePromptBar() ? (formRef()?.clientHeight ?? 0) - 16 : 0}px`,
      }}
      onSubmit={(ev) => {
        ev.preventDefault();

        if (status() || !isSubmittable()) {
          return;
        }

        const model = getCurrentModel();
        if (!model) {
          return;
        }

        setStatus("submitting");

        submitChat(getInputPrompt(), model, { onRespond }).finally(clearStatus);
      }}
    >
      <Button variant="ghost" class="h-4 rounded-none -mx-3 py-0" onClick={() => setHidePromptBar((cur) => !cur)}>
        <ChevronDownIcon class={cn("size-2 transition", hidePromptBar() && "-rotate-180")} />
      </Button>

      <Show when={getInputPrompt().imagePaths}>
        <ImagePreview
          srcs={getInputPrompt().imagePaths ?? []}
          fetcher={fetcher}
          onDelete={deletePreviewItem}
        />
      </Show>

      <textarea
        ref={setTextEntryRef}
        name="prompt"
        value={getInputPrompt().text}
        onInput={(ev) => setInputPrompt("text", ev.currentTarget.value)}
        class="w-full border-none outline-none resize-none bg-transparent max-h-[80dvh] md:max-h-[60dvh] lg:max-h-[30dvh] mx-2"
        placeholder="Enter your prompt here"
        onKeyPress={(ev) => {
          if (ev.key === "Enter" && !ev.shiftKey && !ev.ctrlKey) {
            ev.preventDefault();
            formRef()?.requestSubmit();
          }
        }}
      />

      <div class="flex">
        <div class="grow flex">
          <PromptInputToolbar />
        </div>

        <div class="shrink-0">
          <Show when={busy()} fallback={<SubmitButton />}>
            <Button
              size="icon"
              class="rounded-full"
              type="button"
              title="Stop generation"
              onClick={stopGeneration}
            >
              <img src="/stop-solid.svg" alt="🔲" class="size-5 invert dark:invert-0" />
            </Button>
          </Show>
        </div>
      </div>
    </form>
  );
}

// src/lib/components/sessions/chat-panel/prompt-input.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button"
  import autosize from "autosize"
  import { ArrowUpIcon, ChevronDownIcon, Loader2Icon } from "lucide-svelte"
  import { selectedSessionModel } from "$lib/stores/models"
  import { chatHistory } from "$lib/stores/chats"
  import { emit } from "@tauri-apps/api/event"
  import { cn } from "$lib/utils"
  import { hidePromptBar, inputPrompt, isSubmittable } from "$lib/stores/prompt-input"
  import { get } from "svelte/store"
  import Toolbar from "./prompt-input/toolbar.svelte"
  import ImagePreview from "./prompt-input/image-preview.svelte"
  import { imageCache } from "$lib/stores/images"

  let form = $state<HTMLFormElement | undefined>()
  let textEntry = $state<HTMLTextAreaElement | undefined>()
  let autosizeAttached = false

  function attachAutosize() {
    if (textEntry && !autosizeAttached) {
      autosize(textEntry)
      autosizeAttached = true
    }
  }

  let status = $state<"submitting" | "responding" | undefined>()

  $effect(() => {
    const el = textEntry
    // Workaround to prevent incorrect textarea height
    setTimeout(() => attachAutosize())

    return () => {
      if (el) {
        autosize.destroy(el)
        autosizeAttached = false
      }
    }
  })
</script>

<form
  bind:this={form}
  class={cn(
    "border border-secondary text-secondary-foreground bg-background flex flex-col gap-2 px-3 pt-0 pb-2 rounded-t-3xl overflow-hidden",
    "transition-[margin]",
  )}
  style={`margin-bottom: -${$hidePromptBar ? (form?.clientHeight ?? 0) - 16 : 0}px`}
  onsubmit={(ev) => {
    ev.preventDefault()

    if (status || !get(isSubmittable)) {
      return
    }

    status = "submitting"

    chatHistory.submit(get(inputPrompt), {
      onRespond: () => {
        status = "responding"
        inputPrompt.set({ text: "" })
      },
    }).finally(() => status = undefined)
  }}
>
  <Button
    variant="ghost"
    class="h-4 rounded-none -mx-3 my-0"
    onclick={() => {
      hidePromptBar.update(value => !value)
    }}
    title={$hidePromptBar ? "Expand prompt bar" : "Hide prompt bar"}
  >
    <ChevronDownIcon class={cn(
      "size-2 transition",
      $hidePromptBar && "-rotate-180",
    )} />
  </Button>

  {#if $inputPrompt.imagePaths}
    <ImagePreview paths={$inputPrompt.imagePaths} onDelete={(i) => inputPrompt.update(item => {
      const path = item.imagePaths?.splice(i, 1).at(0)
      if (path) {
        imageCache.delete(path)
      }
      return item
    })} />
  {/if}

  <textarea
    bind:this={textEntry}
    name="prompt"
    bind:value={() => $inputPrompt.text, (v) => inputPrompt.update(o => {
      o.text = v
      return o
    })}
    class="w-full border-none outline-none resize-none bg-transparent max-h-72 mx-2"
    placeholder="Enter your prompt here"
    required
    onkeypress={(ev) => {
      if (ev.key === "Enter" && !ev.shiftKey && !ev.ctrlKey) {
        ev.preventDefault()
        form?.requestSubmit()
      }
    }}
  ></textarea>

  <div class="flex">
    <div class="flex-grow flex">
      <Toolbar />
    </div>

    <div class="flex-shrink-0">
      {#if status === "responding" || $chatHistory?.chats.at(-1)?.status === "sending"}
        <Button
          size="icon"
          class="rounded-full"
          type="button"
          title="Stop"
          onclick={async () => {
            await emit("cancel-gen")
          }}
        >
          <img src="/stop-solid.svg" alt="Stop" class="size-5 invert dark:invert-0" />
        </Button>
      {:else}
        <Button
          size="icon"
          class="rounded-full"
          type="submit"
          disabled={!!status || !$isSubmittable}
          title="Send prompt"
        >
          {#if status === "submitting"}
            <Loader2Icon class="!size-6 animate-spin" />
          {:else}
            <ArrowUpIcon class="!size-6" />
          {/if}
        </Button>
      {/if}
    </div>
  </div>
</form>
