// src/lib/components/sessions/bubble/bubble.svelte
<script lang="ts">
  import type { ChatBubble } from "$lib/models/session"
  import { cn } from "$lib/utils"
  import { Loading } from "$lib/components/ui/command"
  import { parseMarkdown } from "$lib/markdown"

  let { data }: { data: ChatBubble } = $props()

  let content = $derived(data.content)
</script>

<div
  class={cn(
    "marked-area py-2",
    data.role === "user" && "bg-secondary text-secondary-foreground px-5 rounded-2xl",
    data.role === "assistant" && data.status === "sending" && "has-type-block",
  )}
>
  {@html parseMarkdown(content)}
  {#if data.status === "preparing"}
    <Loading />
  {/if}
</div>

// src/lib/components/chat-sessions/chat-panel/chat-bubble/bubble.tsx
import { Show, createMemo } from "solid-js";
import { MarkdownBlock } from "~/lib/components/custom-ui/markdown-block";
import { Progress } from "~/lib/components/ui/progress";
import { useChatEntry } from "~/lib/contexts/chat-entry";
import { cn } from "~/lib/utils/class-names";

export function Bubble() {
  const chat = useChatEntry();
  const role = () => chat?.().role;
  const content = createMemo(() => chat?.().content);
  const status = () => chat?.().status;

  return (
    <div class={cn(
      "py-2",
      role() === "user" && "bg-secondary text-secondary-foreground px-5 rounded-2xl",
    )}>
      <MarkdownBlock markdown={content()} />
      <Show when={status() === "preparing"}>
        <Progress
          value={null}
          class="w-full max-w-md"
        />
      </Show>
    </div>
  );
}
