// src/lib/components/sessions/session-list/operation-dropdown/deletion-dialog.svelte
<script lang="ts">
  import { deleteSession } from "$lib/commands/sessions"
  import Loading from "$lib/components/custom-ui/loading.svelte"
  import { Button, buttonVariants } from "$lib/components/ui/button"
  import { Dialog, DialogClose, DialogContent, DialogFooter, DialogHeader, DialogTrigger } from "$lib/components/ui/dialog"
    import { chatHistory } from "$lib/stores/chats";
  import { sessions } from "$lib/stores/sessions"
  import { cn } from "$lib/utils"
  import { TrashIcon } from "lucide-svelte"
  import { toast } from "svelte-sonner"

  let { sessionId }: { sessionId: number } = $props()

  let open = $state(false)

  let proceeding = $state(false)
</script>

<Dialog bind:open>
  <DialogTrigger
    class={cn(
      "w-full flex gap-2 items-center text-red-600 dark:text-red-400 rounded px-1 py-1",
    )}
  >
    <TrashIcon class="size-4" />
    Delete
  </DialogTrigger>

  <DialogContent>
    <DialogHeader class="font-bold text-lg text-red-600 dark:text-red-400">
      Confirm deletion
    </DialogHeader>

    <div>
      The session and its chat history will be <b>permanently</b> deleted. This operation cannot be undone.
    </div>

    <DialogFooter>
      <DialogClose class={buttonVariants({ variant: "secondary" })} autofocus>
        Cancel
      </DialogClose>
      <Button
        variant="destructive"
        onclick={() => {
          proceeding = true
          deleteSession(sessionId)
            .then(() => {
              open = false

              if ($chatHistory?.session === sessionId) {
                chatHistory.clear()
              }

              toast.success("Session successfully deleted")
              sessions.reload()
            })
            .catch((err) => toast.error(`Error: ${err}`))
            .finally(() => proceeding = false)
        }}
      >
        {#if proceeding}
          <Loading content="Deleting..." />
        {:else}
          Confirm
        {/if}
      </Button>
    </DialogFooter>
  </DialogContent>
</Dialog>

// src/lib/components/chat-sessions/session-list/operations/deletion-dialog.tsx
import { Accessor, Component, createSignal, Match, Switch } from "solid-js";
import { toast } from "solid-sonner";
import { deleteSession } from "~/lib/commands/sessions";
import { LoaderSpin } from "~/lib/components/loader-spin";
import { Button } from "~/lib/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader } from "~/lib/components/ui/dialog";
import { clearChatHistory } from "~/lib/contexts/globals/chat-history";
import { currentSessionId } from "~/lib/contexts/globals/current-session";
import { reloadSessions } from "~/lib/contexts/globals/sessions";

export const DeletionDialog: Component<{
  sessionId: number;
  open?: Accessor<boolean>;
  onOpenChange?: (value: boolean) => void;
}> = (props) => {
  const onOpenChange = (value: boolean) => props.onOpenChange?.(value);

  const [proceeding, setProceeding] = createSignal(false);

  const afterDeletion = (id: number | null) => {
    onOpenChange(false);

    if (currentSessionId() === id) {
      clearChatHistory();
    }

    toast.success("Session successfully deleted");
    reloadSessions();
  };

  return (
    <Dialog open={props.open?.()} onOpenChange={props.onOpenChange}>
      <DialogContent>
        <DialogHeader class="font-bold text-lg text-red-600 dark:text-red-400">Confirm deletion</DialogHeader>
        <div>
          The session and its chat history will be <b>permanently</b> deleted. This operation cannot be undone.
        </div>

        <DialogFooter>
          <Button autofocus variant="secondary" on:click={() => props.onOpenChange?.(false)}>
            Cancel
          </Button>
          <Button
            variant="destructive"
            disabled={proceeding()}
            on:click={() => {
              setProceeding(true);

              const sessionId = props.sessionId;

              deleteSession(sessionId)
                .then(afterDeletion)
                .catch((err) => toast.error(`Error: ${err}`))
                .finally(() => setProceeding(false));
            }}
          >
            <Switch fallback={"Confirm"}>
              <Match when={proceeding()}>
                <LoaderSpin text="Deleting..." />
              </Match>
            </Switch>
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
