// src/lib/components/chat-sessions/session-list/index.tsx
import { clearChatHistory } from "~/lib/contexts/globals/chat-history";
import { Button } from "../../ui/button";
import { PlusIcon } from "lucide-solid";
import { For } from "solid-js";
import { getAllSessions } from "~/lib/contexts/globals/sessions";
import { SessionListItem } from "./item";

export function SessionList() {
  return (
    <div class="w-full h-full flex flex-col">
      <div class="sticky py-4 px-3 flex-shrink-0 flex place-items-center bg-background/50 backdrop-blur-lg">
        <h2 class="text-lg font-bold select-none flex-grow">Sessions</h2>
        <div class="shrink-0">
          <Button
            size="icon"
            variant="outline"
            title="New session"
            onClick={() => clearChatHistory()}
          >
            <PlusIcon />
          </Button>
        </div>
      </div>

      <div class="grow overflow-y-auto">
        <div class="flex flex-col gap-2 px-2">
          <For each={getAllSessions()}>
            {(session) => (
              <SessionListItem sessionId={session.id} title={session.title ?? undefined} />
            )}
          </For>
        </div>
      </div>
    </div>
  );
}

// src/lib/components/chatbox/session-list.svelte
<script lang="ts">
  import { ListBox, ListBoxItem } from "@skeletonlabs/skeleton";
  import { IconDotsVertical, IconMessageCirclePlus } from "@tabler/icons-svelte";
  import { sessionList, currentSession } from "$lib/stores/sessions"
</script>

<div class="flex flex-col px-2 bg-surface-200 dark:bg-surface-800 h-dvh md:w-60 lg:w-80 xl:w-96">
  <div class="flex flex-row place-items-center">
    <span class="flex-auto font-bold px-2 text-lg py-4 select-none">Sessions</span>
    <div>
      <button
        class="btn-icon variant-ghost"
        type="button"
        title="New session"
        on:click={() => currentSession.set(null)}
      >
        <IconMessageCirclePlus />
      </button>
    </div>
  </div>
  <div class="flex-auto overflow-y-scroll">
    <ListBox>
      {#each $sessionList as { id, title } (id)}
        <ListBoxItem bind:group={$currentSession} name="session" value={id} class="group" rounded="rounded-xl" active="variant-ghost">
          <span class="flex-auto truncate">{title}</span>
          <svelte:fragment slot="trail">
            <button type="button" class="btn-icon bg-initial btn-icon-sm opacity-0 group-hover:opacity-100">
              <IconDotsVertical />
            </button>
          </svelte:fragment>
        </ListBoxItem>
      {/each}
    </ListBox>
  </div>
</div>
