// src/routes/models/+page.svelte
<script lang="ts">
  import { ModelDetails, ModelList } from "$lib/components/models"
  import { ResizablePane, ResizablePaneGroup } from "$lib/components/ui/resizable"
  import ResizableHandle from "$lib/components/ui/resizable/resizable-handle.svelte"
  import { activeModels, currentModel } from "$lib/stores/models"
  import { onMount } from "svelte"

  onMount(() => {
    activeModels.reload()

    const timerId = setInterval(() => {
      activeModels.reload()
    }, 10_000)

    return () => {
      clearInterval(timerId)
    }
  })
</script>

<ResizablePaneGroup direction="horizontal">
  <ResizablePane defaultSize={25}>
    <ModelList />
  </ResizablePane>
  <ResizableHandle />
  <ResizablePane>
    <ModelDetails
      model={$currentModel}
      runningInfo={$activeModels.find(({ name }) => name === $currentModel)}
      onExpire={() => {
        activeModels.reload()
      }}
    />
  </ResizablePane>
</ResizablePaneGroup>

// src/routes/models/index.tsx
import { createSignal, onCleanup, onMount } from "solid-js";
import { ModelDetails } from "~/lib/components/model-page/model-details";
import { ModelList } from "~/lib/components/model-page/model-list";
import { Resizable, ResizableHandle, ResizablePanel } from "~/lib/components/ui/resizable";
import { useModelContext } from "~/lib/contexts/model-list";

export default function ModelsPage() {
  const modelContext = useModelContext();

  let [timerId, setTimerId] = createSignal<number>();

  onMount(() => {
    if (modelContext) {
      modelContext.reloadActiveModels();

      setTimerId(
        setInterval(() => {
          modelContext.reloadActiveModels();
        }, 10_000),
      );
    }
  });

  onCleanup(() => {
    clearInterval(timerId());
  });

  return (
    <Resizable orientation="horizontal">
      <ResizablePanel initialSize={0.25}>
        <ModelList />
      </ResizablePanel>
      <ResizableHandle />
      <ResizablePanel initialSize={0.75}>
        <ModelDetails />
      </ResizablePanel>
    </Resizable>
  );
}
