// src/lib/components/custom-ui/model-selector/index.tsx
import { ChevronsUpDownIcon } from "lucide-solid";
import { createMemo, createSignal } from "solid-js";
import { modelList } from "~/lib/contexts/globals/model-states";
import { ModelListItem } from "~/lib/models/model-item";
import {
  Command,
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "../../ui/command";
import { For } from "solid-js";
import { getCurrentModel, setSessionModel } from "~/lib/contexts/globals/current-model";

export function ModelSelector() {
  const [open, setOpen] = createSignal(false);

  const groupedModelList = createMemo(() => {
    return modelList().reduce(
      (acc, cur) => {
        const prefix = cur.name.split(":").at(0) ?? "Misc";
        acc[prefix] = [...(acc[prefix] ?? []), cur];
        return acc;
      },
      {} as Record<string, ModelListItem[]>,
    );
  });

  const updateSessionModel = async (model: string) => {
    await setSessionModel(model);
    setOpen(false);
  };

  return (
    <>
      <button class="flex gap-2 px-4 h-full items-center cursor-pointer" onClick={() => setOpen(true)}>
        <span class="grow truncate text-start w-36 text-sm">{getCurrentModel()}</span>
        <ChevronsUpDownIcon class="size-4" />
      </button>

      <CommandDialog open={open()} onOpenChange={setOpen}>
        <Command>
          <CommandInput placeholder="Search local models" />

          <CommandList>
            <CommandEmpty>No matched model found.</CommandEmpty>
            <For each={Object.entries(groupedModelList())}>
              {([prefix, list]) => (
                <CommandGroup heading={prefix}>
                  <For each={list}>
                    {(item) => (
                      <CommandItem class="cursor-pointer" on:click={() => updateSessionModel(item.name)}>
                        {item.name}
                      </CommandItem>
                    )}
                  </For>
                </CommandGroup>
              )}
            </For>
          </CommandList>
        </Command>
      </CommandDialog>
    </>
  );
}

// src/lib/components/sessions/chat-panel/header/model-selector.svelte
<script lang="ts">
  import { CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "$lib/components/ui/command";
  import type { ModelListItem } from "$lib/models/model-item"
  import { modelList } from "$lib/stores/model-list"
  import { selectedSessionModel } from "$lib/stores/models"
  import { ChevronsUpDownIcon } from "lucide-svelte"

  let open = $state(false)

  async function internalSetSessionModel(model: string): Promise<void> {
    await selectedSessionModel.set(model)
    open = false
  }

  let groupedModelList = $derived($modelList.reduce((acc, cur) => {
    const prefix = cur.name.split(":").at(0) ?? "Misc"

    acc[prefix] = [...acc[prefix] ?? [], cur]
    return acc
  }, {} as { [key: string]: ModelListItem[] }))
</script>

<button
  class="flex gap-2 px-4 h-full items-center"
  onclick={() => open = true}
>
  <span class="flex-grow truncate text-start w-36 text-sm">{$selectedSessionModel}</span>
  <ChevronsUpDownIcon class="size-4" />
</button>

<CommandDialog bind:open>
  <CommandInput
    placeholder="Search local models"
    onclick={(ev) => internalSetSessionModel(ev.currentTarget.value)}
  />
  <CommandList>
    <CommandEmpty>No matched model found.</CommandEmpty>
      {#each Object.entries(groupedModelList) as [prefix, list] (prefix)}
        <CommandGroup heading={prefix}>
          {#each list as { name } (name)}
            <CommandItem onclick={() => internalSetSessionModel(name)}>{name}</CommandItem>
          {/each}
        </CommandGroup>
      {/each}
  </CommandList>
</CommandDialog>
