// src/lib/components/models/model-details.svelte
<script lang="ts" module>
  export function getRemainingSeconds(dateFrom: Date): number {
    return parseInt(((dateFrom.getTime() - new Date().getTime()) / 1000).toFixed(0))
  }
</script>

<script lang="ts">
  import type { ModelInfo, RunningModel } from "$lib/models/model-item"
  import { Tabs, TabsContent, TabsList, TabsTrigger } from "../ui/tabs"
  import { getModel } from "$lib/commands/models"
  import Modelfile from "./model-details/modelfile.svelte"
  import Details from "./model-details/details.svelte"
  import Info from "./model-details/info.svelte"
  import Parameters from "./model-details/parameters.svelte"
  import Template from "./model-details/template.svelte"
  import { defaultModel } from "$lib/stores/models"
  import SetDefault from "./model-details/toolbar/set-default.svelte"
  import Status from "./model-details/status.svelte"
  import { Badge } from "../ui/badge"
  import DuplicateModel from "./model-details/toolbar/duplicate-model.svelte"
  import DeleteModel from "./model-details/toolbar/delete-model.svelte"
  import PlaceholderTitle from "./placeholder-title.svelte"
  import Loading from "../custom-ui/loading.svelte"
  import { toast } from "svelte-sonner"
  import { pullModelTasks } from "$lib/stores/pull-model"
  import ProgressSize from "../custom-ui/progress-size.svelte"
  import { Progress } from "../ui/progress"
  import SystemPrompt from "./model-details/system-prompt.svelte"

  let { model, runningInfo, onExpire }: {
    model?: string
    runningInfo?: RunningModel
    onExpire?: () => void
  } = $props()

  let modelInfo = $state<ModelInfo | undefined>()
  let loading = $state(false)

  let downloadInfo = $derived(model ? $pullModelTasks[model] : undefined)

  $effect(() => {
    modelInfo = undefined

    if (model && (!downloadInfo || downloadInfo.type === "success")) {
      loading = true
      getModel(model).then(result => modelInfo = result)
        .catch(err => toast.error(err))
        .finally(() => loading = false)
    }
  })

  let tabValue = $state<string>("details")
</script>

{#if model}
  <div class="flex flex-col h-full px-4 py-6 gap-4 overflow-y-scroll">
    <div class="border border-border px-4 py-3 rounded flex flex-col gap-3">
      <div class="flex items-center gap-2">
        <h3 class="font-bold text-xl">{model}</h3>
        {#if $defaultModel === model}
          <Badge variant="outline">
            Default
          </Badge>
        {/if}
        <div class="flex-grow"></div>
        <div class="flex gap-2 items-center">
          {#if !downloadInfo}
            {#if $defaultModel !== model}
              <SetDefault {model} />
            {/if}
            <DuplicateModel {model} />
            <DeleteModel {model} />
          {/if}
        </div>
      </div>
      <Status {runningInfo} {onExpire} {downloadInfo} />
    </div>

    <div>
      {#if loading}
        <Loading content="Loading..." />
      {/if}

      {#if downloadInfo && downloadInfo.type === "inProgress"}
        <div class="flex text-sm gap-2 md:gap-4 items-center">
          <Progress
            value={downloadInfo.completed && downloadInfo.total ? downloadInfo.completed / downloadInfo.total * 100 : null}
            class={"h-2 max-w-80"}
          />
          <ProgressSize completedSize={downloadInfo.completed ?? undefined} totalSize={downloadInfo.total ?? undefined} />
        </div>
      {/if}

      {#if modelInfo}
        <Tabs bind:value={tabValue}>
          <TabsList>
            {#if modelInfo.details}
              <TabsTrigger value="details">Details</TabsTrigger>
            {/if}
            <TabsTrigger value="modelfile">Modelfile</TabsTrigger>
            {#if modelInfo.model_info}
              <TabsTrigger value="info">Model Info</TabsTrigger>
            {/if}
            {#if modelInfo.parameters}
              <TabsTrigger value="params">Parameters</TabsTrigger>
            {/if}
            <TabsTrigger value="template">Template</TabsTrigger>
            <TabsTrigger value="system-prompt">System Prompt</TabsTrigger>
          </TabsList>
          <div class="overflow-y-scroll">
            <TabsContent value="modelfile">
              <Modelfile value={modelInfo.modelfile} />
            </TabsContent>
            {#if modelInfo.details}
              <TabsContent value="details">
                <Details value={modelInfo.details} />
              </TabsContent>
            {/if}
            {#if modelInfo.model_info}
              <TabsContent value="info">
                <Info value={modelInfo.model_info} />
              </TabsContent>
            {/if}
            <TabsContent value="params">
              <Parameters value={modelInfo.parameters} />
            </TabsContent>
            <TabsContent value="template">
              <Template value={modelInfo.template} />
            </TabsContent>
            <TabsContent value="system-prompt">
              <SystemPrompt {model} />
            </TabsContent>
          </div>
        </Tabs>
      {/if}
    </div>
  </div>
{:else}
  <div class="flex flex-col place-items-center place-content-center h-full">
    <PlaceholderTitle />
  </div>
{/if}

// src/lib/components/model-page/model-details.tsx
import { createMemo, createResource, createSignal, Match, onMount, Show, Suspense, Switch } from "solid-js";
import { PlaceholderTitle } from "./placeholder-title";
import { Badge } from "../ui/badge";
import { getModel } from "~/lib/commands/models";
import SetDefault from "./toolbar-items/set-default";
import { DuplicateModel } from "./toolbar-items/duplicate-model";
import DeleteModel from "./toolbar-items/delete-model";
import { StatusLine } from "./status-line";
import { LoaderSpin } from "../loader-spin";
import { Progress } from "../ui/progress";
import ProgressSize from "../custom-ui/progress-size";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../ui/tabs";
import { CodeBlock } from "../custom-ui/code-block";
import { Details } from "./sections/details";
import { SystemPromptSection } from "./sections/system-prompt";
import { currentModelPageModel } from "~/lib/contexts/globals/model-page";
import { getTaskMap } from "~/lib/contexts/globals/pull-model-tasks";
import { defaultModel, reloadActiveModels } from "~/lib/contexts/globals/model-states";
import { ProgressEvent } from "~/lib/models/events/progress";
import { ModelInfo } from "./sections/model-info";

function PlaceholderPage() {
  return (
    <div class="flex flex-col items-center place-content-center h-full">
      <PlaceholderTitle />
    </div>
  );
}

interface FetchingProps {
  modelName: string | null;
  downloadInfo?: ProgressEvent;
}

async function fetcher({ modelName, downloadInfo }: FetchingProps) {
  if (!modelName || (downloadInfo && downloadInfo.type !== "success")) {
    return null;
  }

  return await getModel(modelName);
}

export function ModelDetails() {
  const model = () => currentModelPageModel();

  const downloadInfo = createMemo(() => {
    const taskMap = getTaskMap();
    const m = model?.();

    if (taskMap && m) {
      return taskMap[m];
    }

    return undefined;
  });

  const [modelInfo] = createResource(() => ({ modelName: model(), downloadInfo: downloadInfo() }), fetcher);

  onMount(() => {
    reloadActiveModels();
  });

  const [tabValue, setTabValue] = createSignal<string>("details");

  return (
    <Switch fallback={<PlaceholderPage />}>
      <Match when={model?.()}>
        {(m) => (
          <div class="flex flex-col h-full px-4 py-6 gap-4 overflow-y-auto">
            <div class="border border-border px-4 py-3 rounded flex flex-col gap-3">
              <div class="flex items-center gap-2">
                <h3 class="font-bold text-xl">{m()}</h3>
                <Show when={defaultModel() === m()}>
                  <Badge variant="outline">Default</Badge>
                </Show>
                <div class="grow" />
                <div class="flex gap-2 items-center">
                  <Show when={!downloadInfo()}>
                    <Show when={defaultModel?.() !== model?.()}>
                      <SetDefault model={m} />
                    </Show>
                    <DuplicateModel model={m} />
                    <DeleteModel model={m} />
                  </Show>
                </div>
              </div>
              <StatusLine downloadInfo={downloadInfo} model={m} />
            </div>

            <div>
              <Show when={modelInfo.loading}>
                <LoaderSpin text="Loading..." />
              </Show>
              <Show when={downloadInfo()}>
                {(info) => {
                  const infoObj = info();
                  return (
                    infoObj.type === "inProgress" && (
                      <div class="flex text-sm gap-2 md:gap-3.5 items-center">
                        <Progress
                          minValue={0}
                          maxValue={infoObj.total ?? undefined}
                          value={infoObj.completed}
                          class="w-48 md:w-56 lg:w-72 xl:w-96"
                        />
                        <ProgressSize completed={infoObj.completed ?? undefined} total={infoObj.total ?? undefined} />
                      </div>
                    )
                  );
                }}
              </Show>

              <Suspense>
                <Tabs value={tabValue()} onChange={setTabValue}>
                    <Show when={modelInfo()}>
                      {(info) => (
                        <TabsList class="sticky -top-6 z-20">
                          <Show when={info().details}>
                            <TabsTrigger value="details">Details</TabsTrigger>
                          </Show>
                          <TabsTrigger value="modelfile">Modelfile</TabsTrigger>
                          <Show when={info().model_info}>
                            <TabsTrigger value="info">Model Info</TabsTrigger>
                          </Show>
                          <Show when={info().parameters}>
                            <TabsTrigger value="parameters">Parameters</TabsTrigger>
                          </Show>
                          <TabsTrigger value="template">Template</TabsTrigger>
                          <TabsTrigger value="system-prompt">System Prompt</TabsTrigger>
                        </TabsList>
                      )}
                    </Show>

                  <div>
                    <Show when={modelInfo()}>
                      {(info) => (
                        <>
                          <Show when={info().modelfile}>
                            {(content) => (
                              <TabsContent value="modelfile">
                                <CodeBlock code={content()} />
                              </TabsContent>
                            )}
                          </Show>
                          <Show when={info().details}>
                            {(d) => (
                              <TabsContent value="details">
                                <Details value={d()} />
                              </TabsContent>
                            )}
                          </Show>
                          <Show when={info().model_info}>
                            {(mi) => (
                              <TabsContent value="info">
                                <ModelInfo value={mi()} />
                              </TabsContent>
                            )}
                          </Show>
                          <Show when={info().parameters}>
                            {(p) => (
                              <TabsContent value="parameters">
                                <CodeBlock code={p()} />
                              </TabsContent>
                            )}
                          </Show>
                          <Show when={info().template}>
                            {(t) => (
                              <TabsContent value="template">
                                <CodeBlock code={t()} />
                              </TabsContent>
                            )}
                          </Show>
                          <TabsContent value="system-prompt">
                            <SystemPromptSection model={m()} />
                          </TabsContent>
                        </>
                      )}
                    </Show>
                  </div>
                </Tabs>
              </Suspense>
            </div>
          </div>
        )}
      </Match>
    </Switch>
  );
}
