// src/lib/components/models/placeholder-title.svelte
<script lang="ts">
  import { onMount } from "svelte"

  const egg = atob("RGV2aWFudHMsIGZhc2NpbmF0aW5nIGFyZW4ndCB0aGV5Pwo=")
  let eggTriggered = $state(false)

  let text = $state("Oh llama, your llama. 🦙")

  let clickedTimes = $state(0)

  let timerId = $state<number | null>(null)

  function clearTimer() {
    if (timerId !== null) {
      clearTimeout(timerId)
    }
  }

  function resetTimer() {
    clearTimer()
    setTimeout(() => {
      clickedTimes = 0
      timerId = null
    }, 5_000)
  }

  onMount(() => {
    return () => {
      clearTimer()
    }
  })
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_click_events_have_key_events  -->
<span
  class="font-bold text-2xl select-none"
  onclick={() => {
    if (eggTriggered) {
      return
    }

    if (clickedTimes >= 10) {
      eggTriggered = true
      clearTimer()
      text = egg + " 😏"
      return
    }

    clickedTimes++
    resetTimer()
  }}
>
  {text}
</span>

// src/lib/components/model-page/placeholder-title.tsx
import { createEffect, createSignal, onCleanup, Show } from "solid-js";

const TRIGGER_IN_TIMES = 10;

export function PlaceholderTitle() {
  const defaultText = "Oh llama, your llama. 🦙";
  const eggTextBase64 = "RGV2aWFudHMsIGZhc2NpbmF0aW5nIGFyZW4ndCB0aGV5Pwo=";

  const [clickedTimes, setClickedTimes] = createSignal(0);
  const [eggTriggered, setEggTriggered] = createSignal(false);

  const [timerId, setTimerId] = createSignal<number | null>(null);

  const clearTimer = () => {
    const t = timerId();
    if (t !== null) {
      clearTimeout(t);
    }
  };

  const resetTimer = () => {
    clearTimer();
    setTimeout(() => {
      setClickedTimes(0);
      setTimerId(null);
    }, 5_000);
  };

  onCleanup(() => {
    clearTimer();
  });

  createEffect(() => {
    const ct = clickedTimes();

    if (ct >= TRIGGER_IN_TIMES) {
      setEggTriggered(true);
      clearTimer();
    } else if (ct > 0) {
      resetTimer();
    }
  });

  return (
    <span
      class="font-bold text-2xl select-none cursor-pointer"
      onClick={() => {
        if (eggTriggered()) {
          return;
        }

        setClickedTimes((cur) => cur + 1);
      }}
    >
      <Show when={eggTriggered()} fallback={defaultText}>
        {atob(eggTextBase64) + " 😏"}
      </Show>
    </span>
  );
}
