// src/lib/components/chat-sessions/chat-panel/chat-bubble/bubble-sector.tsx
import { createMemo, createSignal, Match, Show, Switch } from "solid-js";
import { ChatImagePreview } from "~/lib/components/custom-ui/image-preview";
import { Avatar, AvatarImage } from "~/lib/components/ui/avatar";
import { useChatEntry } from "~/lib/contexts/chat-entry";
import { cn } from "~/lib/utils/class-names";
import { ThoughtsSection } from "./thoughts-section";
import { Bubble } from "./bubble";
import { BubbleInlineEditor } from "./inline-editor";
import { editPrompt } from "~/lib/contexts/globals/chat-history";
import { VersionPagination } from "./version-pagination";
import { SectorFooter } from "./sector-footer";
import { EditModeProvider } from "~/lib/contexts/edit-mode";
import { LoaderSpin } from "~/lib/components/loader-spin";
import { TriangleAlertIcon } from "lucide-solid";
import { SystemPromptBlock } from "./bubble-sector/system-prompt-block";

export function BubbleSector() {
  const chat = useChatEntry();

  const role = createMemo(() => chat?.().role);
  const model = createMemo(() => chat?.().model);
  const status = createMemo(() => chat?.().status);

  const [editMode, setEditMode] = createSignal(false);

  return (
    <Switch>
      <Match when={role() === "user" || role() === "assistant"}>
        <div
          class={cn(
            "group/bubble-sector flex py-1 gap-2 items-center",
            role() === "user" ? "place-content-end" : "place-content-start",
          )}
        >
          <div class="flex flex-col w-full">
            <div class="flex gap-2 w-full">
              <Show when={role() === "assistant"}>
                <Avatar>
                  {/* TODO: Dynamic avatar */}
                  <AvatarImage src="/ollama.svg" alt="Ollama" class="bg-white p-1 pb-0" />
                </Avatar>
              </Show>

              <div
                class={cn(
                  "flex flex-col gap-1 w-full",
                  role() === "user" && "items-end",
                )}
              >
                <span class="text-xs font-bold">
                  <Switch>
                    <Match when={role() === "assistant"}>
                      {model()}
                    </Match>
                    <Match when={role() === "user"}>
                      You
                    </Match>
                  </Switch>
                </span>

                <Show when={chat?.().imageCount}>
                  {(imageCount) => (
                    <Show when={imageCount() > 0}>
                      <Show when={chat?.().id}>
                        {(id) => (
                          <ChatImagePreview chatId={id()} />
                        )}
                      </Show>
                    </Show>
                  )}
                </Show>

                <Show when={role() === "assistant"}>
                  <ThoughtsSection />
                </Show>

                <Switch fallback={<Bubble />}>
                  <Match when={editMode()}>
                    <BubbleInlineEditor
                      defaultValue={chat?.().content}
                      onCancel={() => setEditMode(false)}
                      onSubmit={(newValue) => {
                        const c = chat?.();
                        const id = c?.id;
                        const model = c?.model;

                        if (id === undefined || model === undefined) {
                          return;
                        }

                        editPrompt({ text: newValue }, id, model, {
                          onRespond() {
                            setEditMode(false);
                          },
                        });
                      }}
                    />
                  </Match>
                </Switch>

                <Show when={chat?.().versions}>
                  <VersionPagination />
                </Show>

                <EditModeProvider accessor={editMode} setter={setEditMode}>
                  <SectorFooter />
                </EditModeProvider>
              </div>
            </div>
          </div>

          <Show when={role() === "user"}>
            <Switch>
              <Match when={status() === "sending"}>
                <LoaderSpin />
              </Match>
              <Match when={status() === "not sent"}>
                <TriangleAlertIcon class="text-yellow-600" />
              </Match>
            </Switch>
          </Show>
        </div>
      </Match>
      <Match when={role() === "system"}>
        <SystemPromptBlock />
      </Match>
    </Switch>
  );
}

// src/lib/components/sessions/bubble/bubble-sector.svelte
<script lang="ts">
  import type { ChatBubble } from "$lib/models/session"
  import { cn } from "$lib/utils"
  import Loading from "$lib/components/custom-ui/loading.svelte"
  import SectorFooter from "./sector-footer.svelte"
  import Bubble from "./bubble.svelte"
  import { Avatar } from "$lib/components/ui/avatar"
  import { TriangleAlertIcon } from "lucide-svelte"
  import VersionPagination from "./version-pagination.svelte"
  import ThoughtsSection from "./thoughts-section.svelte"
  import BubbleEditor from "./bubble-editor.svelte"
  import { chatHistory } from "$lib/stores/chats"
  import AvatarImage from "$lib/components/ui/avatar/avatar-image.svelte"
  import SystemPromptBlock from "./system-prompt-block.svelte"

  let { data }: { data: ChatBubble } = $props()

  let editingMode = $state(false)
</script>

{#if data.role === "user" || data.role === "assistant"}
  <div
    class={cn(
      "group/bubble-sector flex py-1 gap-2 items-center",
      data.role === "user" ? "place-content-end" : "place-content-start",
    )}
  >
    <div class="flex flex-col w-full">
      <div class="flex gap-2 w-full">
        {#if data.role === "assistant"}
          <Avatar>
            <AvatarImage src="/ollama.svg" alt="Ollama logo" class="bg-white p-1 pb-0" />
          </Avatar>
        {/if}

        <div
          class={cn(
            "flex flex-col gap-1 w-full",
            data.role === "user" && "items-end",
          )}
        >
          <span class="text-xs font-bold">
            {#if data.role === "assistant"}
              {data.model}
            {:else if data.role === "user"}
              You
            {/if}
          </span>
          {#if data.role === "assistant"}
            <ThoughtsSection {data} />
          {/if}
          {#if editingMode}
            <BubbleEditor
              defaultValue={data.content}
              onCancel={() => {
                editingMode = false
              }}
              onSubmit={(newValue) => {
                chatHistory.editPrompt({
                  text: newValue,
                }, data.id, {
                  onRespond() {
                    editingMode = false
                  },
                })
              }}
            />
          {:else}
            <Bubble {data} />
          {/if}

          {#if data.versions}
            <div class="flex gap-2 items-center">
              <VersionPagination versions={data.versions} current={data.id} />
            </div>
          {/if}

          <SectorFooter {data} bind:editingMode />
        </div>
      </div>
    </div>

    {#if data.role === "user"}
      {#if data.status === "sending"}
        <Loading />
      {:else if data.status === "not sent"}
        <TriangleAlertIcon class="text-yellow-600" />
      {/if}
    {/if}
  </div>
{:else if data.role === "system"}
  <SystemPromptBlock content={data.content} />
{/if}
