// src/lib/components/chat-sessions/chat-panel/chat-bubble/regen-dropdown.tsx
import { RefreshCwIcon } from "lucide-solid";
import { createMemo, For, Match, Switch } from "solid-js";
import { DropdownMenu, DropdownMenuItem, DropdownMenuTrigger, DropdownMenuContent } from "~/lib/components/ui/dropdown-menu";
import { useChatEntry } from "~/lib/contexts/chat-entry";
import { regenerate } from "~/lib/contexts/globals/chat-history";
import { getSessionWiseModel } from "~/lib/contexts/globals/session-wise-model";

export function RegenDropdown() {
  const chat = useChatEntry();
  const chatId = () => chat?.().id;

  const candidates = createMemo(() => {
    const models = [];

    const current = chat?.().model;
    if (current) {
      models.push(current);
    }

    const sessionModel = getSessionWiseModel();
    if (sessionModel) {
      models.push(sessionModel);
    }

    return [...new Set(models)];
  });

  const dropdownNeeded = createMemo(() => candidates().length > 1);

  const NormalButton = () => {
    return (
      <button
        title="Regenerate"
        onClick={(ev) => {
          ev.preventDefault();
          const id = chatId();
          if (id) {
            regenerate(id);
          }
        }}
      >
        <RefreshCwIcon class="size-4" />
      </button>
    );
  };

  return (
    <Switch fallback={<NormalButton />}>
      <Match when={dropdownNeeded()}>
        <DropdownMenu>
          <DropdownMenuTrigger title="Regenerate">
            <RefreshCwIcon class="size-4" />
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <For each={candidates()}>
              {(modelName) => (
                <DropdownMenuItem
                  class="cursor-pointer"
                  onClick={() => {
                    const id = chatId();
                    if (!id) {
                      return;
                    }

                    regenerate(id, modelName);
                  }}
                >
                  Use {modelName}
                </DropdownMenuItem>
              )}
            </For>
          </DropdownMenuContent>
        </DropdownMenu>
      </Match>
    </Switch>
  );
}

// src/lib/components/sessions/bubble/regen-dropdown.svelte
<script lang="ts">
  import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "$lib/components/ui/dropdown-menu"
  import type { ChatBubble } from "$lib/models/session"
  import { selectedSessionModel } from "$lib/stores/models"
  import { regenerate } from "$lib/utils/regen"
  import { RefreshCwIcon } from "lucide-svelte"

  let { data }: {
    data: ChatBubble,
  } = $props()

  let modelCandidates = $derived([...new Set([
    ...data.model ? [data.model] : [],
    ...$selectedSessionModel ? [$selectedSessionModel] : [],
  ])])

  let dropdownNeeded = $derived(modelCandidates.length > 1)
</script>

{#key `regen-dropdown-${data.id}-${dropdownNeeded}`}
  <DropdownMenu>
    <DropdownMenuTrigger
      title="Regenerate"
      onclick={async (ev) => {
        if (dropdownNeeded) {
          return
        }

        ev.preventDefault()
        await regenerate(data.id)
      }}
    >
      <RefreshCwIcon class="size-4" />
    </DropdownMenuTrigger>

    {#if dropdownNeeded}
      <DropdownMenuContent>
        {#each modelCandidates as name (name)}
          <DropdownMenuItem
            class="cursor-pointer"
            onclick={async () => {
              await regenerate(data.id, name)
            }}
          >
            Use {name}
          </DropdownMenuItem>
        {/each}
      </DropdownMenuContent>
    {/if}
  </DropdownMenu>
{/key}
