// src/lib/components/chat-sessions/chat-panel/chat-bubble/thoughts-section.tsx
import convert from "convert";
import { ChevronDownIcon } from "lucide-solid";
import { createMemo, createSignal, JSX, Match, Show, Switch } from "solid-js";
import { Motion, Presence } from "solid-motionone";
import { LoaderSpin } from "~/lib/components/loader-spin";
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "~/lib/components/ui/collapsible";
import { useChatEntry } from "~/lib/contexts/chat-entry";
import { cn } from "~/lib/utils/class-names";

function ThinkingHints() {
  const chat = useChatEntry();

  const thinking = () => chat?.().thinking;
  const status = () => chat?.().status;

  const thoughtForString = createMemo(() => {
    const thoughtFor = chat?.().thoughtFor;
    if (thoughtFor) {
      const precision = thoughtFor <= 1000 ? 0 : thoughtFor < 60_000 ? 3 : 2;
      return convert(thoughtFor, "milliseconds").to("best").toString(precision);
    }

    return "some time";
  });

  const HintSpan = (props: { children?: JSX.Element }) => (
    <Motion.span
      transition={{ duration: 150 }}
      initial={{ x: -35, opacity: 0 }}
      animate={{ x: 0, opacity: 1 }}
      exit={{ x: 35, opacity: 0 }}
    >
      {props.children}
    </Motion.span>
  );

  return (
    <div class="flex items-center gap-2 text-sm text-muted-foreground">
      <Presence exitBeforeEnter>
        <Switch fallback={(
          <HintSpan>Thought for {thoughtForString()}</HintSpan>
        )}>
          <Match when={thinking() && status() === "sending"}>
            <HintSpan><LoaderSpin text="Thinking..." /></HintSpan>
          </Match>
        </Switch>
      </Presence>
    </div>
  );
}

export function ThoughtsSection() {
  const chat = useChatEntry();

  const [open, setOpen] = createSignal(false);

  return (
    <Show when={chat?.().thoughts || chat?.().thinking}>
      <div>
        <Collapsible open={open()} onOpenChange={setOpen}>
          <div class="flex items-center gap-2 text-sm text-muted-foreground">
            <ThinkingHints />
            <CollapsibleTrigger title={open() ? "Collapse" : "Expand"}>
              <ChevronDownIcon class={cn("size-4 duration-300", open() && "-rotate-180")} />
            </CollapsibleTrigger>
          </div>

          <Presence>
            <CollapsibleContent as={Motion.div}>
              <div></div>
            </CollapsibleContent>
          </Presence>
        </Collapsible>
      </div>
    </Show>
  );
}

// src/lib/components/sessions/bubble/thoughts-section.svelte
<script lang="ts">
  import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "$lib/components/ui/collapsible"
  import { parseMarkdown } from "$lib/markdown"
  import type { ChatBubble } from "$lib/models/session"
  import { cn } from "$lib/utils"
  import convert from "convert"
  import { ChevronDownIcon, Loader2Icon } from "lucide-svelte"
  import { fly } from "svelte/transition"

  let { data }: { data: ChatBubble } = $props()

  let content = $derived(data.thoughts ?? "")
  
  let thoughtForString = $derived(
    data.thoughtFor
      ? convert(data.thoughtFor, "milliseconds")
        .to("best")
        .toString(data.thoughtFor <= 1000 ? 0 : data.thoughtFor < 60_000 ? 3 : 2)
      : "some time"
  )

  let open = $state(false)
</script>

{#if data.thoughts || data.thinking}
  <div>
    <Collapsible bind:open>
      <div class="flex items-center gap-2 text-sm text-muted-foreground">
        {#if data.thinking && data.status === "sending"}
          <span class="flex gap-2 items-center" in:fly={{ x: -25, y: 0 }}>
            <Loader2Icon class="size-4 animate-spin duration-500" />
            Thinking...
          </span>
        {:else}
          <span in:fly={{ x: -25, y: 0 }}>
            Thought for <span>{thoughtForString}</span>
          </span>
        {/if}
        <CollapsibleTrigger title={open ? "Hide thoughts" : "Expand thoughts"}>
          <ChevronDownIcon
            class={cn(
              "size-4 duration-300",
              open && "-rotate-180",
            )}
          />
        </CollapsibleTrigger>
      </div>

      <CollapsibleContent forceMount>
        {#snippet child({ props, open })}
          {#if open}
            <div
              {...props}
              class={cn(
                "marked-area my-1 px-2 md:px-3 py-2 text-muted-foreground bg-muted/50 text-sm rounded",
              )}
              transition:fly={{ x: 0, y: -20 }}
            >
              {@html parseMarkdown(content) }
            </div>
          {/if}
        {/snippet}
      </CollapsibleContent>
    </Collapsible>
  </div>
{/if}
