// src/lib/components/chat-sessions/chat-panel/chat-bubble/version-pagination.tsx
import { ChevronLeftIcon, ChevronRightIcon } from "lucide-solid";
import { createMemo, createSignal, Show } from "solid-js";
import { LoaderSpin } from "~/lib/components/loader-spin";
import { useChatEntry } from "~/lib/contexts/chat-entry";
import { switchBranch } from "~/lib/contexts/globals/chat-history";

export function VersionPagination() {
  const chat = useChatEntry();

  const versions = () => chat?.().versions;
  const current = () => chat?.().id;

  const page = createMemo(() => {
    const pageIndex = versions()?.findIndex((id) => id === current());
    if (pageIndex === undefined) {
      return undefined;
    }

    return pageIndex + 1;
  });

  const [switching, setSwitching] = createSignal(false);

  const switchToPage = (pageNum: number) => {
    if (switching()) return;

    const ver = versions();
    if (!ver) {
      return;
    }

    setSwitching(true);
    switchBranch(ver[pageNum - 1])
      .finally(() => setSwitching(false));
  };

  return (
    <Show when={versions()?.length}>
      {(length) => (
        <Show when={length() > 1}>
          <div class="flex gap-1 items-center text-muted-foreground font-bold text-xs">
            <Show when={page()}>
              {(p) => (
                <button
                  disabled={p() <= 1}
                  class="disabled:opacity-0"
                  onClick={() => switchToPage(p() - 1)}
                >
                  <ChevronLeftIcon class="size-3" />
                </button>
              )}
            </Show>

            <Show when={!switching()} fallback={<LoaderSpin class="size-3" />}>
              <span>{page?.()}</span> / <span>{versions()?.length}</span>
            </Show>

            <Show when={page()}>
              {(p) => (
                <button
                  disabled={p() >= length()}
                  class="disabled:opacity-0"
                  onClick={() => switchToPage(p() + 1)}
                >
                  <ChevronRightIcon class="size-3" />
                </button>
              )}
            </Show>
          </div>
        </Show>
      )}
    </Show>
  );
}

// src/lib/components/sessions/bubble/version-pagination.svelte
<script lang="ts">
  import MicroButton from "$lib/components/custom-ui/micro-button.svelte"
  import { chatHistory } from "$lib/stores/chats"
  import { ChevronLeftIcon, ChevronRightIcon, Loader2Icon } from "lucide-svelte"

  let { versions, current }: {
    versions: number[]
    current: number
  } = $props()

  let page = $derived(versions.findIndex(id => id === current) + 1)
  let switching = $state(false)
</script>

{#if versions.length > 1}
  <div class="flex gap-1 items-center text-muted-foreground font-bold text-xs">
    <MicroButton
      disabled={page <= 1}
      class="disabled:opacity-0"
      onclick={() => {
        if (switching) return

        switching = true
        chatHistory.switchBranch(versions[page - 2])
          .finally(() => switching = false)
      }}
    >
      <ChevronLeftIcon class="size-3" />
    </MicroButton>

    {#if switching}
      <Loader2Icon class="size-3 animate-spin" />
    {:else}
      <span>{page}</span>
      /
      <span>{versions.length}</span>
    {/if}

    <MicroButton
      disabled={page >= versions.length}
      class="disabled:opacity-0"
      onclick={() => {
        if (switching) return

        switching = true
        chatHistory.switchBranch(versions[page])
          .finally(() => switching = false)
      }}
    >
      <ChevronRightIcon class="size-3" />
    </MicroButton>
  </div>
{/if}
