// src/lib/components/chat-sessions/chat-panel/index.tsx
import { Component } from "solid-js";
import { PromptInput } from "../prompt-input";
import { ChatFeeds } from "./chat-feeds";
import { ChatPanelHeader } from "./header";

export const ChatPanel: Component = () => {
  return (
    <div class="flex flex-col w-full h-full overflow-y-hidden">
      <ChatPanelHeader />

      <div class="grow px-4 py-2 w-full overflow-y-auto">
        <ChatFeeds />
      </div>

      <div class="max-w-5xl w-full mx-auto">
        <PromptInput />
      </div>
    </div>
  );
}

// src/lib/components/sessions/chat-panel.svelte
<script lang="ts">
  import Header from "./chat-panel/header.svelte"
  import ChatFeeds from "./chat-panel/chat-feeds.svelte"
  import PromptInput from "./chat-panel/prompt-input.svelte"
</script>

<div class="flex flex-col w-full h-full">
  <Header />
  <div class="flex-grow px-2 py-2 max-w-screen-lg mx-auto">
    <ChatFeeds />
  </div>
  <div class="max-w-screen-lg mx-auto">
    <PromptInput />
  </div>
</div>
