// src/lib/components/chat-sessions/session-list/index.tsx
import { clearChatHistory } from "~/lib/contexts/globals/chat-history";
import { Button } from "../../ui/button";
import { PlusIcon } from "lucide-solid";
import { For } from "solid-js";
import { getAllSessions } from "~/lib/contexts/globals/sessions";
import { SessionListItem } from "./item";

export function SessionList() {
  return (
    <div class="w-full h-full flex flex-col">
      <div class="sticky py-4 px-3 flex-shrink-0 flex place-items-center bg-background/50 backdrop-blur-lg">
        <h2 class="text-lg font-bold select-none flex-grow">Sessions</h2>
        <div class="shrink-0">
          <Button
            size="icon"
            variant="outline"
            title="New session"
            onClick={() => clearChatHistory()}
          >
            <PlusIcon />
          </Button>
        </div>
      </div>

      <div class="grow overflow-y-auto">
        <div class="flex flex-col gap-2 px-2">
          <For each={getAllSessions()}>
            {(session) => (
              <SessionListItem sessionId={session.id} title={session.title ?? undefined} />
            )}
          </For>
        </div>
      </div>
    </div>
  );
}

// src/lib/components/sessions/session-list.svelte
<script lang="ts">
  import { PlusIcon } from "lucide-svelte"
  import Button from "../ui/button/button.svelte"
  import { ScrollArea } from "../ui/scroll-area"
  import { currentSessionId, sessions } from "$lib/stores/sessions"
  import SessionListItem from "./session-list/session-list-item.svelte"

</script>

<div class="w-full h-full flex flex-col">
  <div class="py-4 px-3 flex-shrink-0 flex place-items-center">
    <h2 class="text-lg font-bold select-none flex-grow">Sessions</h2>
    <div class="flex-shrink-0">
      <Button
        size="icon"
        variant="outline"
        title="New session"
        onclick={() => {
          $currentSessionId = undefined
        }}
      >
        <PlusIcon />
      </Button>
    </div>
  </div>
  <ScrollArea class="flex-grow">
    <div class="flex flex-col gap-2 px-2">
      {#if $sessions}
        {#each $sessions as { id, title } (id)}
          <SessionListItem sessionId={id} {title} />
        {/each}
      {/if}
    </div>
  </ScrollArea>
</div>
