// src/lib/components/model-page/model-list-item.tsx
import { TriangleAlertIcon, XIcon } from "lucide-solid";
import { createMemo, Match, Show, Switch } from "solid-js";
import { useModelContext } from "~/lib/contexts/model-list";
import { useModelPageCurrentModel } from "~/lib/contexts/model-page/current-model";
import { cn } from "~/lib/utils/class-names";
import { LoaderSpin } from "../loader-spin";
import StatusDot from "../custom-ui/status-dot";
import { Badge } from "../ui/badge";
import { usePullModelTasks } from "~/lib/contexts/pull-model-tasks";
import { emit } from "@tauri-apps/api/event";
import { toEventString } from "~/lib/utils/strings";
import { toast } from "solid-sonner";
import RelativeTime from "../custom-ui/relative-time";
import ProgressSize from "../custom-ui/progress-size";
import { Progress } from "../ui/progress";

export interface ModelListItemProps {
  name: string;
  message?: string;
  totalSize?: number;
  modifiedAt?: Date;
  completedSize?: number;
  status?: "inProgress" | "failure" | "canceled";
  index: number;
}

export function ModelListItem(props: ModelListItemProps) {
  const modelPageCurrentModel = useModelPageCurrentModel();
  const modelContext = useModelContext();
  const pullModelTasksContext = usePullModelTasks();

  const currentModel = modelPageCurrentModel?.[0];
  const setCurrentModel = modelPageCurrentModel?.[1];
  const defaultModel = modelContext?.defaultModel;

  const selected = createMemo(() => currentModel?.() === props.name);
  const isDefault = createMemo(() => defaultModel?.() === props.name);

  const completed = () => props.completedSize;
  const total = () => props.totalSize;

  const status = () => props.status;

  const progressPrecentage = createMemo(() => {
    if (status() !== "inProgress") {
      return undefined;
    }

    const c = completed();
    const t = total();

    if (c !== undefined && t !== undefined) {
      return c / t * 100;
    }

    return undefined;
  });
  
  const name = () => props.name;
  const message = () => props.message;

  return (
    <div
      class={cn(
        "flex flex-col rounded cursor-pointer overflow-hidden",
        selected() ? "bg-primary text-primary-foreground" : "bg-secondary text-secondary-foreground",
      )}
      role="button"
      tabindex={props.index}
      on:click={(ev) => {
        setCurrentModel?.(props.name);
        ev.stopPropagation();
      }}
    >
      <div class="flex flex-col px-2 py-2 gap-2">
        <div class="flex items-center select-none gap-1">
          <Switch>
            <Match when={status() === "failure"}>
              <TriangleAlertIcon class="size-4" />
            </Match>
            <Match when={status() === "inProgress"}>
              <LoaderSpin class="size-4" />
            </Match>
          </Switch>

          <span class="font-bold">{name()}</span>

          <Show when={modelContext?.activeModels().map(item => item.name).includes(name())}>
            <StatusDot status="success" />
          </Show>

          <Show when={isDefault()}>
            <Badge
              variant={selected() ? "secondary" : "default"}
              title="Newly created sessions will use this model."
            >
              Default
            </Badge>
          </Show>

          <div class="grow"></div>
          <Show when={status()}>

            {(s) => (
              <button
                title={s() === "canceled" ? "Remove" : "Cancel"}
                onClick={() => {
                  if (s() === "canceled" || s() === "failure") {
                    pullModelTasksContext?.clear(name());
                  } else {
                    const promise = emit(`cancel-pull/${toEventString(name())}`);

                    toast.promise(promise, {
                      loading: "Cancel request sent",
                      success: "Pulling task canceled",
                      error: (err) => `Error: ${err}`,
                    });
                  }
                }}
              >
                <XIcon class="size-4" />
              </button>
            )}
          </Show>
        </div>

        <div class="flex items-center text-xs gap-1">
          <Show when={message()}>
            {(msg) => (
              <span class="truncate">{msg()}</span>
            )}
          </Show>
          <Show when={props.modifiedAt}>
            {(ma) => (
              <span class="flex gap-1">
                Modified
                <RelativeTime date={ma()} />
              </span>
            )}
          </Show>
          <div class="grow"></div>
          <ProgressSize completed={completed()} total={total()} />
        </div>
      </div>

      <Progress
        value={progressPrecentage()}
        class={cn(
          "h-1 rounded-none bg-transparent",
          selected() && "invert",
        )}
      />
    </div>
  );
}

// src/lib/components/models/model-list/model-list-item.svelte
<script lang="ts">
  import { cn } from "$lib/utils"
  import { activeModels, currentModel, defaultModel } from "$lib/stores/models"
  import StatusDot from "$lib/components/custom-ui/status-dot.svelte"
  import { Badge } from "$lib/components/ui/badge";
  import RelativeTime from "$lib/components/custom-ui/relative-time.svelte"
  import { Progress } from "$lib/components/ui/progress"
  import { Loader2Icon, TriangleAlertIcon, XIcon } from "lucide-svelte"
  import MicroButton from "$lib/components/custom-ui/micro-button.svelte"
  import ProgressSize from "$lib/components/custom-ui/progress-size.svelte"
  import { pullModelTasks } from "$lib/stores/pull-model"
  import { emit } from "@tauri-apps/api/event"
  import { toEventString } from "$lib/utils/strings"
  import { toast } from "svelte-sonner"

  let {
    name,
    message,
    totalSize,
    completedSize,
    modifiedAt,
    status,
    index: i,
  }: {
    name: string
    message?: string
    totalSize?: number
    completedSize?: number
    modifiedAt?: Date
    status?: "inProgress" | "failure" | "canceled"
    index: number,
  } = $props()

  let selected = $derived($currentModel === name)
  let isDefault = $derived($defaultModel === name)

  let completeProgress = $derived(completedSize !== undefined && totalSize !== undefined)

</script>

<!-- svelte-ignore a11y_click_events_have_key_events  -->
<div
  class={cn(
    "flex flex-col rounded cursor-pointer overflow-hidden",
    selected ? "bg-primary text-primary-foreground" : "bg-secondary text-secondary-foreground",
  )}
  role="button"
  tabindex={i}
  onclick={(ev) => {
    currentModel.set(name)
    ev.stopPropagation()
  }}
>
  <div
    class="flex flex-col px-2 py-2 gap-2"
  >
    <div class="flex items-center select-none gap-1">
      {#if status === "failure"}
        <TriangleAlertIcon class="size-4" />
      {/if}
      {#if status === "inProgress"}
        <Loader2Icon class="size-4 animate-spin" />
      {/if}
      <span class="font-bold">{name}</span>
      {#if $activeModels.map(item => item.name).includes(name)}
        <StatusDot status="success" />
      {/if}

      {#if isDefault}
        <Badge
          variant={selected ? "secondary" : "default"}
          title="Newly created sessions will use this model by default."
        >
          Default
        </Badge>
      {/if}

      <div class="flex-grow"></div>
      {#if status}
        <MicroButton
          title={status === "canceled" ? "Remove" : "Cancel"}
          onclick={() => {
            if (status === "canceled" || status === "failure") {
              pullModelTasks.clear(name)
            } else {
              const promise = emit(`cancel-pull/${toEventString(name)}`)

              toast.promise(promise, {
                loading: "Cancel request sent",
                success: "Pulling task canceled",
                error: (err) => `Error: ${err}`,
              })
            }
          }}
        >
          <XIcon class="size-4" />
        </MicroButton>
      {/if}
    </div>

    <div class="flex items-center text-xs gap-1">
      {#if message}
        <span class="truncate">{message}</span>
      {/if}
      {#if modifiedAt !== undefined}
        <span class="flex gap-1">
          Modified
          <RelativeTime date={modifiedAt} />
        </span>
      {/if}
      <div class="flex-grow"></div>
      <ProgressSize {completedSize} {totalSize} />
    </div>
  </div>
  <Progress
    value={status === "inProgress" ? (completeProgress ? completedSize! / totalSize! * 100 : null) : undefined}
    class={cn(
      "h-1 rounded-none bg-transparent",
      selected && "invert",
    )}
  />
</div>
