// src/lib/components/model-page/pull-model/index.tsx
import { createMemo, createSignal, Match, Show, Switch } from "solid-js";
import { Button } from "~/lib/components/ui/button";
import { CloudDownloadIcon } from "lucide-solid";
import { CommandDialog, CommandGroup, CommandInput, CommandList } from "~/lib/components/ui/command";
import { BASE_DOMAIN, BASE_URL, useModelSearchResult } from "~/lib/contexts/model-search-result";
import { openUrl } from "@tauri-apps/plugin-opener";
import { Motion, Presence } from "solid-motionone";
import { platform } from "@tauri-apps/plugin-os";
import { LoaderSpin } from "../../loader-spin";

interface HintsProps {
  searchEntered?: boolean;
}

function Hints(props: HintsProps) {
  const searchEntered = () => props.searchEntered;

  const os = createMemo(() => platform());

  return (
    <Show when={searchEntered()}>
      <Motion.div
        class="flex gap-2 md:gap-4 lg:gap-6 text-xs px-2 py-2"
        transition={{ duration: 300 }}
        initial={{ x: -100, opacity: 0 }}
        animate={{ x: 0, opacity: 1 }}
        exit={{ x: -100, opacity: 1 }}
      >
        <span class="flex gap-2 items-center">
          <span class="z-[1]"><kbd>Enter</kbd></span>
          Search
        </span>
        <span class="flex gap-2 items-center">
          <span>
            <Switch fallback={<><kbd>Ctrl</kbd> + <kbd>Enter</kbd></>}>
              <Match when={os() === "macos" || os() === "ios"}>
                <kbd>{"\u2318" /* Command key symbol */} Enter</kbd>
              </Match>
            </Switch>
          </span>
          <span>Pull entered anyway</span>
        </span>
      </Motion.div>
    </Show>
  );
}

export function PullModel() {
  const searchResultContext = useModelSearchResult();

  const keyword = () => searchResultContext?.keyword() ?? "";
  const searchResult = () => searchResultContext?.searchResult;
  const initiateSearch = (keyword: string) => searchResultContext?.initiateSearch(keyword);

  const [open, setOpen] = createSignal(false);

  const [inputKeyword, setInputKeyword] = createSignal<string>(keyword());

  return (
    <>
      <Button
        size="icon"
        variant="outline"
        title="Pull model"
        onClick={() => setOpen(true)}
      >
        <CloudDownloadIcon />
      </Button>

      <CommandDialog open={open()} onOpenChange={setOpen}>
        <CommandInput
          placeholder={`Search models on ${BASE_DOMAIN}`}
          disabled={searchResult()?.loading}
          value={inputKeyword()}
          onValueChange={setInputKeyword}
          on:keydown={(ev) => {
            if (ev.key === "End") {
              ev.preventDefault()
              ev.stopPropagation()
              const value = ev.currentTarget.value
              ev.currentTarget.setSelectionRange(value.length, value.length)
              return
            }

            if (ev.key === "Home") {
              ev.preventDefault()
              ev.stopPropagation()
              ev.currentTarget.setSelectionRange(0, 0)
            }

            if (ev.key === "Enter") {
              ev.preventDefault()

              if (ev.ctrlKey) {
                searchResultContext?.startPullModel(keyword());
                setInputKeyword("");
              } else {
                initiateSearch(keyword());
              }
            }
          }}
        />

        <div class="flex">
          <Button
            variant="link"
            size="sm"
            class="text-xs flex gap-0"
            onClick={() => {
              const kw = keyword();
              openUrl(kw.length > 0 ? `${BASE_URL}/search?` + new URLSearchParams({ q: kw }) : BASE_URL);
            }}
          >
            <span class="z-[1]">Visit {BASE_DOMAIN}</span>
              <Presence exitBeforeEnter>
                <Show when={inputKeyword().trim()}>
                  {(kw) => (
                    <Show when={kw().length > 0}>
                      <Motion.span
                        class="-ml-[1pt]"
                        transition={{ duration: 300 }}
                        initial={{ opacity: 0, x: -30 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: -30 }}
                      >
                        &nbsp;with "{kw()}"
                      </Motion.span>
                    </Show>
                  )}
                </Show>
              </Presence>
          </Button>
        </div>

        <Hints searchEntered={inputKeyword().trim().length > 0} />

        <CommandList>
          <Show when={searchResult()?.loading}>
            <div class="px-2 py-2 text-sm">
              <LoaderSpin text="Searching..." />
            </div>
          </Show>
          <Show when={searchResult()}>
            {(s) => (
              <CommandGroup heading="Search result">
              </CommandGroup>
            )}
          </Show>
        </CommandList>
      </CommandDialog>
    </>
  );
}

// src/lib/components/models/model-list/pull-model.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button"
  import { CommandDialog, CommandEmpty, CommandInput, CommandList } from "$lib/components/ui/command"
  import { CloudDownloadIcon } from "lucide-svelte"
  import Hints from "./pull-model/hints.svelte"
  import { BASE_DOMAIN, BASE_URL, type SearchResult } from "$lib/stores/model-search"
  import Loading from "$lib/components/custom-ui/loading.svelte"
  import { toast } from "svelte-sonner"
  import { searchModel } from "$lib/search/model-search"
  import SearchResultSection from "./pull-model/search-result-section.svelte"
  import { fly } from "svelte/transition"
  import { openUrl } from "@tauri-apps/plugin-opener"

  let open = $state(false)

  let keyword = $state("")

  let searchResult = $state<SearchResult | undefined>()
  let searching = $state(false)

  let isPullNext = $derived(searchResult !== undefined && keyword === searchResult.keyword)

  function startPullModel(model: string) {
    open = false
  }

  async function startSearchModels() {
    if (searching) {
      return
    }

    searching = true
    try {
      searchResult = {
        keyword,
        category: "all",
        orderedBy: "popular",
        result: Array.from(await searchModel(keyword)),
      }
    } catch (e) {
      toast.error(`${e}`)
      return
    } finally {
      searching = false
    }
  }
</script>

<Button
  size="icon"
  variant="outline"
  title="Pull model"
  onclick={() => {
    open = true
  }}
>
  <CloudDownloadIcon />
</Button>

<CommandDialog
  bind:open
  shouldFilter={false}
>
  <CommandInput
    placeholder={`Search model on ${BASE_DOMAIN}`}
    bind:value={() => keyword, (newValue) => (keyword = newValue.trim())}
    disabled={searching}
    onkeydown={(ev) => {
      if (ev.key === "End") {
        ev.preventDefault()
        const value = ev.currentTarget.value
        ev.currentTarget.setSelectionRange(value.length, value.length)
        return
      }

      if (ev.key === "Home") {
        ev.preventDefault()
        ev.currentTarget.setSelectionRange(0, 0)
      }

      if (ev.key === "Enter") {
        ev.preventDefault()

        if (ev.ctrlKey) {
          startPullModel(keyword)
        } else {
          startSearchModels()
        }
      }
    }}
  />
  <div class="flex">
    <Button
      variant="link"
      size="sm"
      class="text-xs flex gap-0"
      onclick={async () => {
        await openUrl(keyword.length > 0 ? `${BASE_URL}/search?` + new URLSearchParams({ q: keyword }) : BASE_URL)
      }}
    >
      <span class="z-[1]">Visit {BASE_DOMAIN}</span>
      {#if keyword.length > 0}
        <span class="-ml-[1px]" transition:fly={{ x: -30, y: 0, duration: 300 }}>
          &nbsp;with "{keyword}"
        </span>
      {/if}
    </Button>
  </div>
  <Hints searchEntered={keyword.length > 0} {isPullNext} />
  <CommandList>
    {#if searching}
      <div class="px-2 py-2 text-sm">
        <Loading content="Searching..." />
      </div>
    {/if}
    {#if searchResult !== undefined}
      <SearchResultSection
        {searchResult}
        {isPullNext}
        onInitiatePull={(model) => {
          startPullModel(model)
        }}
      />
    {/if}
    <CommandEmpty>No model found.</CommandEmpty>
  </CommandList>
</CommandDialog>
