// src/lib/components/model-page/pull-model.tsx
import { createSignal } from "solid-js";
import { Button } from "../ui/button";
import { CloudDownloadIcon } from "lucide-solid";
import { CommandDialog, CommandInput } from "../ui/command";
import { BASE_DOMAIN, useModelSearchResult } from "~/lib/contexts/model-search-result";

export function PullModel() {
  const searchResultContext = useModelSearchResult();

  const keyword = () => searchResultContext?.keyword() ?? "";
  const searchResult = () => searchResultContext?.searchResult;
  const initiateSearch = (keyword: string) => searchResultContext?.initiateSearch(keyword);

  const [open, setOpen] = createSignal(false);

  return (
    <>
      <Button
        size="icon"
        variant="outline"
        title="Pull model"
        onClick={() => setOpen(true)}
      >
        <CloudDownloadIcon />
      </Button>

      <CommandDialog open={open()} onOpenChange={setOpen}>
        <CommandInput
          placeholder={`Search models on ${BASE_DOMAIN}`}
          disabled={searchResult()?.loading}
          on:keydown={(ev) => {
            if (ev.key === "End") {
              ev.preventDefault()
              ev.stopPropagation()
              const value = ev.currentTarget.value
              ev.currentTarget.setSelectionRange(value.length, value.length)
              return
            }

            if (ev.key === "Home") {
              ev.preventDefault()
              ev.stopPropagation()
              ev.currentTarget.setSelectionRange(0, 0)
            }

            if (ev.key === "Enter") {
              ev.preventDefault()

              if (ev.ctrlKey) {
              } else {
                initiateSearch(keyword());
              }
            }
          }}
        />
      </CommandDialog>
    </>
  );
}

// src/lib/components/models/model-list/pull-model.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button"
  import { CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandList } from "$lib/components/ui/command"
  import { CloudDownloadIcon } from "lucide-svelte"
  import Hints from "./pull-model/hints.svelte"
  import { BASE_DOMAIN, type SearchItem } from "$lib/stores/model-search"
  import Loading from "$lib/components/custom-ui/loading.svelte"

  let open = $state(false)

  let keyword = $state("")

  let searchResult = $state<SearchItem[] | undefined>()
  let searching = $state(false)
</script>

<Button
  size="icon"
  variant="outline"
  title="Pull model"
  onclick={() => {
    open = true
  }}
>
  <CloudDownloadIcon />
</Button>

<CommandDialog
  bind:open
  shouldFilter={false}
>
  <CommandInput
    placeholder={`Pull model from ${BASE_DOMAIN}`}
    bind:value={() => keyword, (newValue) => (keyword = newValue)}
    disabled={searching}
  />
  <Hints searchEntered={keyword.length > 0} searchInitiated={searchResult !== undefined} />
  <CommandList>
    <CommandEmpty>No model found.</CommandEmpty>
    {#if searchResult !== undefined}
      <CommandGroup heading="Search result">
      </CommandGroup>
    {/if}
    {#if searching}
      <div class="px-2 py-2 text-sm">
        <Loading content="Searching..." />
      </div>
    {/if}
  </CommandList>
</CommandDialog>
