// src/lib/components/model-page/pull-model/search-result-item.tsx
import { SearchItem, useModelSearchResult } from "~/lib/contexts/model-search-result";
import { CommandItem } from "../../ui/command";
import { Component, createMemo, createSignal } from "solid-js";
import { modelList } from "~/lib/contexts/globals/model-states";
import { getTaskMap } from "~/lib/contexts/globals/pull-model-tasks";
import { For, JSX, Match, Switch } from "solid-js";
import { cn } from "~/lib/utils/class-names";
import { Button } from "../../ui/button";
import { LoaderSpin } from "../../loader-spin";
import { CloudDownloadIcon } from "lucide-solid";

const TagBadge: Component<{
  children?: JSX.Element;
  class?: string;
  "on:click"?: (ev: MouseEvent) => void;
}> = (props) => {
  const clickHandler = (ev: MouseEvent) => props["on:click"]?.(ev);

  return (
    <span class={cn("text-xs px-2 py-1 rounded-lg", props.class)} on:click={clickHandler}>
      {props.children}
    </span>
  );
}

export const SearchResultItem: Component<{
  item: SearchItem;
  ["on:startDownloading"]?: () => void;
}> = (props) => {
  const LATEST = "latest";

  const searchResultContext = useModelSearchResult();

  const searchItem = () => props.item;

  const [selected, setSelected] = createSignal<string>(LATEST);
  const fullName = createMemo(() => `${props.item.name}:${selected()}`);

  const downloadedAlready = createMemo(() => {
    const modelName = fullName();
    return modelList().filter(({ name }) => name === modelName).length > 0;
  });
  const downloading = createMemo(() => Object.keys(getTaskMap()).includes(fullName()));

  return (
    <CommandItem onClick={() => setSelected(LATEST)} class="flex flex-col">
      <div class="flex flex-col gap-2 w-full">
        <span class="font-bold">{searchItem().name}</span>
        <span class="whitespace-pre-wrap flex-wrap">{searchItem().description}</span>
      </div>
      <div class="flex gap-2 w-full">
        <div class="flex gap-2 items-center">
          <For each={searchItem().tags}>
            {(tag) => (
              <Switch>
                <Match when={tag.type === "category"}>
                  <TagBadge class="bg-fuchsia-200/80 dark:bg-fuchsia-900/80">{tag.content}</TagBadge>
                </Match>
                <Match when={tag.type === "parameter"}>
                  <TagBadge
                    class={cn(
                      "bg-sky-200/80 dark:bg-sky-900/80 hover:bg-sky-300 dark:hover:bg-sky-800 cursor-pointer",
                      selected() === tag.content && "bg-sky-400 dark:bg-sky-700",
                    )}
                    on:click={(ev) => {
                      ev.stopPropagation();
                      setSelected(tag.content);
                    }}
                  >
                    {tag.content}
                  </TagBadge>
                </Match>
              </Switch>
            )}
          </For>
        </div>
        <div class="grow" />
        <div class="flex gap-2 lg:gap-4 place-content-end text-xs items-center">
          <span>Selected: {selected()}</span>
          <Button
            size="icon"
            variant="ghost"
            on:click={(ev) => {
              ev.stopPropagation();
              searchResultContext?.startPullModel(fullName());
              props["on:startDownloading"]?.();
            }}
            disabled={downloadedAlready()}
          >
            <Switch
              fallback={<CloudDownloadIcon class={cn("size-4", downloadedAlready() && "text-muted-foreground")} />}
            >
              <Match when={downloading()}>
                <LoaderSpin class="size-4" />
              </Match>
            </Switch>
          </Button>
        </div>
      </div>
    </CommandItem>
  );
}

// src-svelte/lib/components/models/model-list/pull-model/search-result-item.svelte
<script lang="ts">
  import MicroButton from "$lib/components/custom-ui/micro-button.svelte"
  import TagBadge from "$lib/components/custom-ui/tag-badge.svelte"
  import { CommandLinkItem } from "$lib/components/ui/command"
  import { modelList } from "$lib/stores/model-list"
  import type { SearchItem } from "$lib/stores/model-search"
  import { pullModelTasks } from "$lib/stores/pull-model"
  import { cn } from "$lib/utils"
  import { CloudDownloadIcon, Loader2Icon } from "lucide-svelte"

  let {
    item,
    onInitiatePull,
  }: {
    item: SearchItem
    onInitiatePull?: (model: string) => void
  } = $props()

  let selected = $state<string>("latest")
  let fullName = $derived(`${item.name}:${selected}`)

  let downloadedAlready = $derived($modelList.filter(({ name }) => name === fullName).length > 0)
  let downloading = $derived(Object.keys($pullModelTasks).includes(fullName))

  let downloadInitiated = $state(false)

  $effect(() => {
    if (downloading) {
      downloadInitiated = false
    }
  })
</script>

<CommandLinkItem
  onclick={() => selected = "latest"}
>
  <div class="flex flex-col gap-2 w-full">
    <div class="flex flex-col">
      <span class="font-bold">{item.name}</span>
      <span class="whitespace-pre-wrap flex-wrap">
        {item.description}
      </span>
    </div>
    <div class="flex gap-2 w-full">
      <div class="flex gap-2">
        {#each item.tags as { type, content } (content)}
          {#if type === "category"}
            <TagBadge class="bg-fuchsia-200/80 dark:bg-fuchsia-900/80">{content}</TagBadge>
          {:else if type === "parameter"}
            <TagBadge
              class={cn(
                "bg-sky-200/80 dark:bg-sky-900/80 hover:bg-sky-400 dark:hover:bg-sky-700 cursor-pointer",
                selected === content && "bg-sky-400 dark:bg-sky-700",
              )}
              onclick={(ev) => {
                ev.stopPropagation()
                selected = content
              }}
            >
              {content}
            </TagBadge>
          {/if}
        {/each}
      </div>
      <div class="flex-grow"></div>
      <div class="flex gap-2 lg:gap-4 place-content-end text-xs items-center">
        <span>Selected: {selected}</span>
        <MicroButton
          title={downloadedAlready ? "Model downloaded already" : "Pull model"}
          onclick={(ev) => {
            ev.stopPropagation()
            downloadInitiated = true
            onInitiatePull?.(fullName)
          }}
          disabled={downloadedAlready}
        >
          {#if downloadInitiated || downloading}
            <Loader2Icon class="size-4 animate-spin" />
          {:else}
            <CloudDownloadIcon class={cn("size-4", downloadedAlready && "text-muted-foreground")} />
          {/if}
        </MicroButton>
      </div>
    </div>
  </div>
</CommandLinkItem>
