// src/lib/components/sessions/bubble/status.svelte
<script lang="ts">
  import type { Role, TransmissionStatus } from "$lib/models/session"
  import { cn } from "$lib/utils"

  let { role, status }: {
    role: Role
    status: TransmissionStatus
  } = $props()

  const text: { [role: string]: { [status: string]: string } } = {
    user: {
      sent: "sent",
      "not sent": "failed",
    },
    assistant: {
      preparing: "initializing",
      sending: "generating",
      sent: "generated",
      "not sent": "not completed",
    },
  }
</script>

<div class="flex gap-1 items-center">
  <span
    class={cn(
      "uppercase font-light",
    )}
  >
    {text[role]?.[status]}
  </span>
</div>

// src/lib/components/chat-sessions/chat-panel/chat-bubble/bubble-sector/status.tsx
import { Show } from "solid-js";
import { useChatEntry } from "~/lib/contexts/chat-entry";

export function BubbleSectorFooterStatus() {
  const chat = useChatEntry();
  const role = () => chat?.().role;
  const status = () => chat?.().status;

  const text: Record<string, Record<string, string>> = {
    user: {
      sent: "sent",
      "not sent": "failed",
    },
    assistant: {
      preparing: "initializing",
      sending: "generating",
      sent: "generated",
      "not sent": "not completed",
    },
  }

  return (
    <div class="flex gap-1 items-center">
      <span class="uppercase font-light">
        <Show when={role()}>
          {(r) => (
            <Show when={status()}>
              {(s) => (
                <span>{text[r()]?.[s()]}</span>
              )}
            </Show>
          )}
        </Show>
      </span>
    </div>
  );
}
