// src/lib/components/app-bar/tab-link.svelte
<script lang="ts">
  import { cn } from "$lib/utils"
  import type { Snippet } from "svelte"

  let { children, name, href, active, onClick }: {
    children?: Snippet
    name: string
    href?: string
    active?: boolean
    onClick?: () => void
  } = $props()
</script>

<div class={cn("group flex m-1 rounded cursor-pointer", active && "bg-secondary")}>
  <div class="py-1">
    <hr
      class={cn(
        "border h-full border-transparent rounded-full",
        active ? "border-primary" : "group-hover:border-secondary",
      )}
    />
  </div>
  <a
    href={href ?? "#"}
    aria-label={name}
    title={name}
    draggable={false}
    class={cn(
      "p-3",
    )}
    onclick={onClick}
  >
    {@render children?.()}
  </a>
</div>

// src/lib/components/app-bar/tab-link.tsx
import { A } from "@solidjs/router";
import { Component, createMemo, JSX } from "solid-js";
import { cn } from "~/lib/utils/class-names";

export const TabLink: Component<{
  children?: JSX.Element;
  name: string;
  href?: string;
  active?: boolean;
  onClick?: () => void;
}> = (props) => {
  const active = createMemo(() => props.active);
  const href = () => props.href;
  const name = createMemo(() => props.name);

  return (
    <div class={cn("group flex rounded cursor-pointer", active() && "bg-secondary")} onClick={() => props.onClick?.()}>
      <div class="py-1">
        <hr
          class={cn(
            "border h-full border-transparent rounded-full",
            active() ? "border-primary" : "group-hover:border-secondary",
          )}
        />
      </div>

      <A href={href() ?? ""} aria-label={name()} title={name()} draggable={false} class="p-3">
        {props.children}
      </A>
    </div>
  );
}
