// src/lib/components/model-page/toolbar-items/delete-model.tsx
import { Accessor, createSignal, Match, Show, Switch } from "solid-js";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "../../ui/dialog";
import { TrashIcon } from "lucide-solid";
import { Button } from "../../ui/button";
import { LoaderSpin } from "../../loader-spin";
import { deleteModel } from "~/lib/commands/models";
import { useModelContext } from "~/lib/contexts/model-list";
import { toast } from "solid-sonner";

export interface DeleteModelProps {
  model: Accessor<string>;
}

export default function DeleteModel(props: DeleteModelProps) {
  const modelContext = useModelContext();

  const model = props.model;

  const [open, setOpen] = createSignal(false);
  const [submitting, setSubmitting] = createSignal(false);

  return (
    <Dialog open={open()} onOpenChange={setOpen}>
      <DialogTrigger as={Button<"button">} title="Delete" size="icon" variant="destructive">
        <TrashIcon />
      </DialogTrigger>

      <DialogContent>
        <DialogHeader>
          <DialogTitle class="text-red-700 dark:text-red-500">
            <Switch fallback={"Confirm deletion"}>
              <Match when={submitting()}>
                <LoaderSpin text="Deleting model..." />
              </Match>
            </Switch>
          </DialogTitle>
        </DialogHeader>

        <Show when={!submitting()}>
          <div>
            The model will be <b>permanently</b> deleted.
          </div>

          <DialogFooter>
            <Button type="button" variant="secondary" onClick={() => setOpen(false)}>
              Cancel
            </Button>
            <Button
              type="submit"
              variant="destructive"
              onClick={() => {
                setSubmitting(true);
                const deletionPromise = deleteModel(model())
                  .then(() => {
                    setOpen(false);
                    modelContext?.setCurrent(null);
                    modelContext?.reload();
                  })
                  .finally(() => setSubmitting(false));

                toast.promise(deletionPromise, {
                  loading: "Deleting model...",
                  success: "Model successfully deleted",
                  error: (err) => {
                    return `Deletion failed: ${err}`;
                  },
                });
              }}
            >
              Confirm
            </Button>
          </DialogFooter>
        </Show>
      </DialogContent>
    </Dialog>
  );
}

// src-svelte/lib/components/models/model-details/toolbar/delete-model.svelte
<script lang="ts">
  import { deleteModel } from "$lib/commands/models"
  import Loading from "$lib/components/custom-ui/loading.svelte"
  import { Button, buttonVariants } from "$lib/components/ui/button"
  import { Dialog, DialogClose, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "$lib/components/ui/dialog"
  import { modelList } from "$lib/stores/model-list"
  import { currentModel } from "$lib/stores/models"
  import { cn } from "$lib/utils"
  import { TrashIcon } from "lucide-svelte"
  import { toast } from "svelte-sonner"

  let { model }: { model: string } = $props()

  let open = $state(false)
  let submitting = $state(false)
</script>

<Dialog bind:open>
  <DialogTrigger
    class={cn(buttonVariants({ variant: "destructive", size: "icon" }))}
    title="Delete"
  >
    <TrashIcon />
  </DialogTrigger>

  <DialogContent>
    <DialogHeader>
      <DialogTitle class="text-red-700 dark:text-red-500">
        {#if submitting}
          <Loading content={"Deleting model..."} />
        {:else}
          Confirm deletion
        {/if}
      </DialogTitle>
    </DialogHeader>
    {#if !submitting}
      <div>
        The model will be <b>permanently</b> removed.
      </div>
      <DialogFooter>
        <DialogClose
          class={cn(buttonVariants({ variant: "secondary" }))}
        >
          Cancel
        </DialogClose>
        <Button
          variant="destructive"
          onclick={() => {
            submitting = true
            const deletionPromise = deleteModel(model)
              .then(() => {
                open = false
                currentModel.set(undefined)
                modelList.reload()
              })
              .finally(() => submitting = false)

            toast.promise(deletionPromise, {
              loading: "Deleting model...",
              success: "Model successfully deleted",
              error: (err) => {
                return `Deletion failed: ${err}`
              },
            })
          }}
        >
          Confirm
        </Button>
      </DialogFooter>
    {/if}
  </DialogContent>
</Dialog>
