// src-svelte/lib/components/ui/progress/progress.svelte
<script lang="ts">
	import { Progress as ProgressPrimitive, type WithoutChildrenOrChild } from "bits-ui";
	import { cn } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		max = 100,
		value,
		...restProps
	}: WithoutChildrenOrChild<ProgressPrimitive.RootProps> = $props();
</script>

<ProgressPrimitive.Root
	bind:ref
	class={cn("bg-secondary relative h-4 w-full overflow-hidden rounded-full", className)}
	{value}
	{max}
	{...restProps}
>
	<div
		class={cn(
          "bg-primary h-full w-full flex-1 transition-all rounded-full",
          value === null && "animate-indeterminate",
        )}
		style={value === null ? undefined : `transform: translateX(-${100 - (100 * (value ?? 0)) / (max ?? 1)}%)`}
	></div>
</ProgressPrimitive.Root>

// src/lib/components/ui/progress/index.tsx
import type { ComponentProps } from "solid-js";
import { createMemo, splitProps } from "solid-js";

import { cn } from "~/lib/utils/class-names";

export interface ProgressProps extends ComponentProps<"div"> {
  value?: number | null;
  minValue?: number;
  maxValue?: number;
}

export function Progress(props: ProgressProps) {
  const [local, other] = splitProps(props, ["class", "value", "minValue", "maxValue"]);

  const percentage = createMemo(() => {
    if (props.value === null) {
      return undefined;
    }

    const maxValue = props.maxValue === undefined ? 100 : props.maxValue;
    const minValue = props.minValue ?? 0;
    const value = Math.min(Math.max(props.value ?? 0, minValue), maxValue);

    return (value - minValue) / (maxValue - minValue);
  });

  const transformStyle = createMemo(() => {
    const p = percentage();
    return typeof p === "number" ? `${p * 100 - 100}%` : undefined;
  });

  return (
    <div class={cn("relative h-2 overflow-hidden rounded-full bg-secondary", local.class)} {...other}>
      <div
        class={cn(
          "h-full transition-transform bg-primary rounded-full",
          local.value === null && "animate-indeterminate",
        )}
        style={{
          translate: transformStyle(),
        }}
      />
    </div>
  );
}
