// src/lib/components/sessions/chat-panel/header.svelte
<script lang="ts">
  import ModelSelector from "./header/model-selector.svelte"

</script>

<div class="sticky flex-shrink-0 border-b border-border h-12 flex items-center backdrop-blur-lg bg-background/50">
  <div class="flex-grow flex gap-2">
    <ModelSelector />
  </div>

  <div class="px-2">
  </div>
</div>

// src/lib/components/chat-sessions/chat-panel/header.tsx
import { Component } from "solid-js";
import { ModelSelector } from "../../custom-ui/model-selector";

export const ChatPanelHeader: Component = () => {
  return (
    <div class="sticky shrink-0 border-b border-border h-12 flex items-center backdrop-blur-lg bg-background/50">
      <div class="grow flex gap-2">
        <ModelSelector />
      </div>
    </div>
  );
};
